### ISSUE TITLE
Error on Ubuntu 18.04.4 with Erlang 11.0.2 OTP23

### ISSUE THREAD

**Issue by davidrutt1** [erlangpack/bcrypt#13]
I get this error when trying to use this on Ubuntu.
Assume there is some mismatch on underlying version of software installed, but what?
Anybody have any ideas on this?

```
{ok, Salt} = bcrypt:gen_salt().
** exception exit: {noproc,{gen_server,call,
                                       [nif_pool,
                                        {checkout,#Ref<0.199613538.3797417985.209039>,true},
                                        5000]}}
```

**Comment by mworrell** [comment]
Did you start the application?

Afaik all tests run on Ubuntu, so I won't expect a problem with the specific OS.

**Comment by mworrell** [comment]
Hi David, do you still experience this problem?

**Comment by davidrutt1** [comment]
Upgrades to all components eventually fixed this issue.

**Comment by mworrell** [comment]
Thanks for checking back in, and great to hear that all runs well now.
